### ISSUE TITLE
Fix random missing name

### ISSUE THREAD

**Issue by LeamHall** [makhidkarun/ftl_tools#11]
Sometimes happens, sometimes not.
 
 2) crewgen has a pilot
     Failure/Error: erb :crew
     
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./views/person.erb:1:in `block in singleton class'
     # ./views/person.erb:-6:in `instance_eval'
     # ./views/person.erb:-6:in `singleton class'
     # ./views/person.erb:-9:in `__tilt_47051051702680'
     # ./views/crew.erb:30:in `block in singleton class'
     # ./views/crew.erb:-6:in `instance_eval'
     # ./views/crew.erb:-6:in `singleton class'
     # ./views/crew.erb:-9:in `__tilt_47051051702680'
     # ./lib/ftl_tools/crewgen.rb:63:in `block in <class:CrewGen>'
     # ./spec/unit/crewgen_spec.rb:23:in `block (2 levels) in <module:FTLTools>'

**Comment by LeamHall** [comment]
Issue was that the medic was not required on 100 ton ships, so there was no medic. FIxed the template to only show crew positions that are used.
